apiVersion: batch/v1
kind: Job
metadata:
  name: comments-on-semi-parametric-sampling-job-5
spec:
  template:
    metadata:
      labels:
        app: comments-on-semi-parametric-sampling-job
      name: comments-on-semi-parametric-sampling-job
    spec:
      containers:
      - args:
        - --name
        - final_experiment_5
        - --steps
        - '200000'
        - --save_every
        - '50000'
        - --arms_nb
        - '1000'
        - --d
        - '5'
        - --gcs_bucket_path
        - gs://semi-parametric-sampling-bucket
        - --reward_distribution
        - binomial
        - --seed
        - '6'
        - --a
        - '1.0'
        - --sigma_1
        - '0.1'
        - --sigma_2
        - '0.1'
        - --sigma_3
        - '1.0'
        - --v
        - '1.0'
        - --models
        - LinearSemiParametricSampling
        - LinearGaussianSampling
        - GaussianPriorsSampling
        - BetaPriorsSampling
        image: "gcr.io/semi-parametric-sampling/semi-parametric-sampling:latest
        name: semi-parametric-sampling
        resources:
          requests:
            memory: 5000Mi
      restartPolicy: Never
